apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: dq56f9rl3-dotnet-basic
  janus-idp.io/tekton: dq56f9rl3-dotnet-basic
  backstage.io/kubernetes-id: dq56f9rl3-dotnet-basic
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: dq56f9rl3-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
